# Generated by Django 5.2.4 on 2025-07-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='الرمز')),
                ('program', models.CharField(max_length=255, verbose_name='البرنامج')),
                ('projects', models.TextField(verbose_name='المشاريع')),
                ('location', models.CharField(max_length=255, verbose_name='المكان')),
                ('district', models.CharField(max_length=255, verbose_name='المقاطعة/الجماعة')),
                ('planning_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرمز في تصميم التهيئة')),
                ('components', models.TextField(verbose_name='مكونات المشروع')),
                ('target_group', models.TextField(verbose_name='الفئة المستهدفة')),
                ('property_status', models.CharField(max_length=100, verbose_name='وضعية العقار')),
                ('property_drawing', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرسم العقاري')),
                ('area', models.DecimalField(decimal_places=2, help_text='بالمتر المربع', max_digits=10, verbose_name='المساحة')),
                ('property_prep_cost', models.DecimalField(decimal_places=2, help_text='بالدرهم المغربي', max_digits=15, verbose_name='كلفة تعبئة العقار')),
                ('studies', models.TextField(blank=True, null=True, verbose_name='الدراسات')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='الإنجازات')),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='بالدرهم المغربي', max_digits=15, verbose_name='التكلفة التقديرية')),
                ('start_year', models.PositiveIntegerField(verbose_name='سنة الانطلاق')),
                ('estimated_duration', models.PositiveIntegerField(verbose_name='المدة التقديرية (أشهر)')),
                ('implementation_years', models.CharField(max_length=100, verbose_name='سنوات التنفيذ')),
                ('budget_years', models.CharField(max_length=100, verbose_name='سنوات الميزانية')),
                ('indicator_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='المؤشر 1')),
                ('indicator_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='المؤشر 2')),
                ('indicator_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='المؤشر 3')),
                ('potential_partners', models.TextField(blank=True, null=True, verbose_name='الشركاء المحتملين')),
                ('funding_sources', models.TextField(blank=True, null=True, verbose_name='مصادر التمويل المحتملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
    ]
