# Generated by Django 5.2.4 on 2025-07-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='development_goals',
            field=models.TextField(blank=True, help_text='أدخل الأهداف التنموية للمشروع', null=True, verbose_name='الأهداف التنموية'),
        ),
    ]
