# Generated by Django 5.2.4 on 2025-07-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_development_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_goals',
            field=models.TextField(blank=True, help_text='أدخل الأهداف الرئيسية للمشروع', null=True, verbose_name='أهداف المشروع'),
        ),
    ]
