# Generated by Django 5.2.4 on 2025-07-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget_years',
            field=models.JSONField(default=list, help_text='اختر سنوات الميزانية', verbose_name='سنوات الميزانية'),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_years',
            field=models.JSONField(default=list, help_text='اختر سنوات التنفيذ', verbose_name='سنوات التنفيذ'),
        ),
    ]
