# Generated by Django 5.2.4 on 2025-08-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_budget_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_launch_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إطلاق السوق')),
                ('actual_costs', models.DecimalField(blank=True, decimal_places=2, help_text='بالدرهم المغربي', max_digits=15, null=True, verbose_name='التكاليف الفعلية')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء المخطط')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء الفعلي')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('cost_variance_percentage', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='الفرق في التكلفة (%)')),
                ('delay_rate', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='معدل التأخير')),
                ('delay_variance_days', models.IntegerField(blank=True, editable=False, null=True, verbose_name='الفرق في الأيام')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'تتبع المشروع',
                'verbose_name_plural': '',
            },
        ),
    ]
