# Generated by Django 5.2.4 on 2025-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projecttracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracking',
            name='notes',
            field=models.TextField(blank=True, help_text='أي ملاحظات إضافية حول تقدم المشروع', null=True, verbose_name='ملاحظات'),
        ),
    ]
