# Generated by Django 5.2.4 on 2025-08-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projecttracking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracking',
            name='estimated_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='التكاليف التقديرية بالدرهم المغربي', max_digits=15, verbose_name='التكلفة التقديرية (ب)'),
        ),
        migrations.AddField(
            model_name='projecttracking',
            name='potential_partners',
            field=models.TextField(blank=True, null=True, verbose_name='الشركاء المحتملين'),
        ),
        migrations.AddField(
            model_name='projecttracking',
            name='programming_date',
            field=models.DateField(blank=True, null=True, verbose_name='سنة الانطلاق'),
        ),
        migrations.AddField(
            model_name='projecttracking',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المشروع'),
        ),
        migrations.AlterField(
            model_name='projecttracking',
            name='actual_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='التكاليف الفعلية بالدرهم المغربي', max_digits=15, verbose_name='التكاليف الفعلية (أ)'),
        ),
        migrations.AlterField(
            model_name='projecttracking',
            name='cost_variance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='(ب-أ)/ب * 100', max_digits=10, null=True, verbose_name='نسبة التباين في التكلفة (ج)'),
        ),
        migrations.AlterField(
            model_name='projecttracking',
            name='delay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='(تاريخ الانتهاء الفعلي - تاريخ الانتهاء المخطط) / 100', max_digits=10, null=True, verbose_name='معدل التأخير'),
        ),
        migrations.AlterField(
            model_name='projecttracking',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='projects.project', verbose_name='كود المشروع'),
        ),
    ]
