# Generated by Django 5.1.7 on 2025-08-18 05:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projecttracking_estimated_costs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttracking',
            name='estimated_costs',
        ),
        migrations.RemoveField(
            model_name='projecttracking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='projecttracking',
            name='potential_partners',
        ),
        migrations.RemoveField(
            model_name='projecttracking',
            name='programming_date',
        ),
        migrations.RemoveField(
            model_name='projecttracking',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='projecttracking',
            name='actual_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='بالدرهم المغربي', max_digits=15, null=True, verbose_name='التكاليف الفعلية'),
        ),
        migrations.AlterField(
            model_name='projecttracking',
            name='cost_variance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='الفرق في التكلفة (%)'),
        ),
        migrations.AlterField(
            model_name='projecttracking',
            name='delay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='معدل التأخير'),
        ),
        migrations.AlterField(
            model_name='projecttracking',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='projects.project', verbose_name='المشروع'),
        ),
        migrations.CreateModel(
            name='ExecutionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='بالدرهم المغربي', max_digits=15, null=True, verbose_name='المبلغ المبرمج')),
                ('partner_contribution', models.DecimalField(blank=True, decimal_places=2, help_text='بالدرهم المغربي', max_digits=15, null=True, verbose_name='تعبئة الشركاء')),
                ('programming_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البرمجة')),
                ('market_launch_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إطلاق الصفقات')),
                ('actual_costs', models.DecimalField(blank=True, decimal_places=2, help_text='بالدرهم المغربي', max_digits=15, null=True, verbose_name='التكاليف الفعلية (أ)')),
                ('estimated_costs', models.DecimalField(blank=True, decimal_places=2, help_text='بالدرهم المغربي', max_digits=15, null=True, verbose_name='التكاليف التقديرية (ب)')),
                ('cost_difference_percentage', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='فرق التكلفة (%)')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء المتوقع')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية الفعلية')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('delay_percentage', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='معدل التأخير (%)')),
                ('duration_difference_days', models.IntegerField(blank=True, editable=False, null=True, verbose_name='فرق المدة (بالأيام)')),
                ('work_progress_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='معدل التقدم (%) للأشغال')),
                ('financial_achievement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='معدل الإنجاز (%) (مالي)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_rates', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'معدل التنفيذ',
                'verbose_name_plural': 'معدلات التنفيذ',
                'ordering': ['-created_at'],
            },
        ),
    ]
